syntax = "proto3";

package bilibili.app.archive.middleware.v1;

// 视频秒开参数
message PlayerArgs {
    // 清晰度
    int64 qn = 1;
    // 流版本
    int64 fnver = 2;
    // 流类型
    int64 fnval = 3;
    // 返回url是否强制使用域名
    // 0:不强制使用域名 1:http域名 2:https域名
    int64 force_host = 4;
    // 音量均衡
    int64 voice_balance = 5;
    // 清晰度选择策略
    QnPolicy qn_policy = 6;
    // 客户端属性
    int64 client_attr = 7;
    // 额外参数
    map<string, string> extra_content = 8;
    // 软解功能标记
    int64 soft_fnval = 9;
}

// 清晰度选择策略
enum QnPolicy {
    // 默认策略
    QN_POLICY_DEFAULT = 0;
    // 允许自动选择清晰度
    QN_POLICY_AUTO_QN_ENABLE = 1;
}
